projectName: "testit-api-client"
projectDescription: "Api client for Test IT TMS"
npmVersion: 7.0.0
licenseName: "Apache-2.0"
npmRepository: "https://www.npmjs.com/package/testit-api-client"
supportsES6: true
platform: node
projectVersion: "7.0.0-rc3"
usePromises: true
